services:
  ros2_dev:
    build: .
    container_name: ros2_project
    image: ros2_project_image
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/root/ros2_ws/src
    #map webcam to the container
    devices:
      - /dev/video0:/dev/video0
    working_dir: /root/ros2_ws
    command: bash -c "source /opt/ros/humble/setup.bash && sleep infinity"
